###############################################
# Network For The Servarr
###############################################

networks:
  servarrnetwork:
    name: servarrnetwork
    ipam:
      config:
        - subnet: 172.39.0.0/24

services:
  ###############################################
  # Gluetun - VPN
  ###############################################
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      servarrnetwork:
        ipv4_address: ${IP_GLUETUN}
    ports:
      - 8080:8080 # qbittorrent web interface
      - 6881:6881 # qbittorrent torrent port
      - 9696:9696 # prowlarr
      - 8191:8191 # flaresolverr
    volumes:
      - ./gluetun:/gluetun
    # Make a '.env' file in the same directory as compose file.
    env_file:
      - .env
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 20s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  ###############################################
  # DEUNHEALTH - Monitors containers
  ###############################################
  deunhealth:
    image: qmcgaw/deunhealth
    container_name: deunhealth
    network_mode: "none"
    environment:
      - LOG_LEVEL=info
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
      - TZ=${TZ}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ###############################################
  # RADARR - Movies
  ###############################################
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 7878:7878
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/radarr:/config
      - /data:/data
    networks:
      servarrnetwork:
        ipv4_address: ${IP_RADARR}

  ###############################################
  # SONARR - TV Shows
  ###############################################
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8989:8989
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sonarr:/config
      - /data:/data
    networks:
      servarrnetwork:
        ipv4_address: ${IP_SONARR}

  ###############################################
  # LIDARR - Music
  ###############################################
  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8686:8686
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/lidarr:/config
      - /data:/data
    networks:
      servarrnetwork:
        ipv4_address: ${IP_LIDARR}

  ###############################################
  # BAZARR - Subtitles
  ###############################################
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 6767:6767
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/bazarr:/config
      - /data/media:/data/media
    networks:
      servarrnetwork:
        ipv4_address: ${IP_BAZARR}

  ###############################################
  # PROWLARR - Indexer Manager
  ###############################################
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/prowlarr:/config
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    network_mode: service:gluetun

  ###############################################
  # QBITTORRENT - Downloader
  ###############################################
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent:latest
    restart: unless-stopped
    labels:
      - deunhealth.restart.on.unhealthy=true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080 # must match "qbittorrent web interface" port number in gluetun's service above
      - TORRENTING_PORT=${FIREWALL_VPN_INPUT_PORTS} # airvpn forwarded port, pulled from .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/qbittorrent:/config
      - /data:/data
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    network_mode: service:gluetun
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s

  ###############################################
  # SEERR - Request Manager
  ###############################################
  seerr:
    container_name: seerr
    image: ghcr.io/hotio/seerr:latest
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/seerr:/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    networks:
      servarrnetwork:
        ipv4_address: ${IP_SEERR}

  ###############################################
  # REQUESTRR - Request Bot
  ###############################################
  requestrr:
    container_name: requestrr
    image: ghcr.io/hotio/requestrr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 4545:4545
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/requestrr:/config
    networks:
      servarrnetwork:
        ipv4_address: ${IP_REQUESTRR}

  ###############################################
  # PLEX - Media Server
  ###############################################
  plex:
    container_name: plex
    image: ghcr.io/hotio/plex:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/plex:/config
      - /data/media:/data/media:ro #read-only
    networks:
      servarrnetwork:
        ipv4_address: ${IP_PLEX}

  ###################################
  # PROFILARR - Import Quailty Profiles
  ###################################
  profilarr:
    container_name: profilarr
    image: santiagosayshey/profilarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 6868:6868
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/profilarr:/config
    networks:
      servarrnetwork:
        ipv4_address: ${IP_PROFILARR}

  ###################################
  # FLARESOLVERR - Cloudflare Bypass
  ###################################
  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
      network_mode: service:gluetun

  ###############################################
  # DISPATCHARR - IPTV Companion
  ###############################################
  dispatcharr:
    container_name: dispatcharr
    image: ghcr.io/dispatcharr/dispatcharr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DISPATCHARR_ENV=aio
      - REDIS_HOST=localhost
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - DISPATCHARR_LOG_LEVEL=info
    ports:
      - 9191:9191
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/dispatcharr:/data
    networks:
      servarrnetwork:
        ipv4_address: ${IP_DISPATCHARR}

  ###############################################
  # RECLAIMERR - Manage Your Media
  ###############################################
  reclaimerr:
    container_name: reclaimerr
    image: ghcr.io/jessielw/reclaimerr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8000:8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data:/opt/data
    networks:
      servarrnetwork:
        ipv4_address: ${IP_RECLAIMERR}

  ###############################################
  # CLEANUPARR - Keep Everything Clean
  ###############################################
  cleanuparr:
    container_name: cleanuparr
    image: ghcr.io/cleanuparr/cleanuparr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 11011:11011
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/cleanuparr:/config
    networks:
      servarrnetwork:
        ipv4_address: ${IP_CLEANUPARR}

  ###############################################
  # TAUTULLI - Monitor Media Server
  ###############################################
  tautulli:
    container_name: tautulli
    image: ghcr.io/hotio/tautulli:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8181:8181
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/tautulli:/config
    networks:
      servarrnetwork:
        ipv4_address: ${IP_TAUTULLI}

  ###############################################
  # HOMEPAGE - Dashboard
  ###############################################
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - HOMEPAGE_ALLOWED_HOSTS=gethomepage.dev
    ports:
      - 3000:3000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/homepage:/config
    networks:
      servarrnetwork:
        ipv4_address: ${IP_HOMEPAGE}
###############################################
###############################################
